import type { Clinic } from "@/lib/supabase/database.types";

/**
 * Datos de ejemplo con la misma forma que la fila real de `clinics`.
 * Sirven para construir y ver la UI mientras no hay credenciales de
 * Supabase conectadas. Los nombres de las clínicas son ficticios.
 *
 * Cuando conectemos Supabase, esta función se sustituye por una
 * consulta real (`supabase.from("clinics").select("*")`) sin tocar
 * los componentes que la consumen.
 */
export const mockClinics: Clinic[] = [
  {
    id: "1",
    slug: "raiz-capilar-madrid",
    nombre: "Raíz Capilar Madrid",
    descripcion:
      "Clínica especializada en injertos capilares de alta densidad, con seguimiento fotográfico durante todo el proceso de recuperación.",
    comunidad_autonoma: "Comunidad de Madrid",
    provincia: "Madrid",
    ciudad: "Madrid",
    zona: "Salamanca",
    lat: 40.4168,
    lng: -3.7038,
    telefono: "+34 910 123 456",
    email: "hola@raizcapilarmadrid.example",
    web: "https://raizcapilarmadrid.example",
    redes_sociales: { instagram: "raizcapilarmadrid", facebook: "raizcapilarmadrid" },
    tecnicas: ["Injerto FUE", "Injerto DHI", "Mesoterapia capilar"],
    idiomas: ["Español", "Inglés"],
    financiacion: true,
    primera_consulta_gratis: true,
    fotos: ["https://picsum.photos/seed/growwly-madrid-1/800/600"],
    verificado: true,
    created_at: "2026-01-10T09:00:00.000Z",
    updated_at: "2026-06-01T09:00:00.000Z",
  },
  {
    id: "2",
    slug: "instituto-vaila-barcelona",
    nombre: "Instituto Vaila de Tricología",
    descripcion:
      "Diagnóstico tricológico detallado antes de cada tratamiento, con equipo médico propio y sin subcontratar el injerto.",
    comunidad_autonoma: "Cataluña",
    provincia: "Barcelona",
    ciudad: "Barcelona",
    zona: "Eixample",
    lat: 41.3874,
    lng: 2.1686,
    telefono: "+34 933 456 789",
    email: "info@institutovaila.example",
    web: "https://institutovaila.example",
    redes_sociales: { instagram: "institutovaila" },
    tecnicas: ["Injerto FUE", "Injerto sin afeitado", "PRP"],
    idiomas: ["Español", "Inglés", "Francés"],
    financiacion: true,
    primera_consulta_gratis: false,
    fotos: ["https://picsum.photos/seed/growwly-barcelona-1/800/600"],
    verificado: true,
    created_at: "2026-01-15T09:00:00.000Z",
    updated_at: "2026-05-20T09:00:00.000Z",
  },
  {
    id: "3",
    slug: "centro-renova-palma",
    nombre: "Centro Renova Capilar",
    descripcion:
      "Clínica boutique en el centro de Palma, atiende sobre todo a pacientes internacionales que combinan el tratamiento con unos días de vacaciones.",
    comunidad_autonoma: "Illes Balears",
    provincia: "Illes Balears",
    ciudad: "Palma",
    zona: "Centro",
    lat: 39.5696,
    lng: 2.6502,
    telefono: "+34 971 234 567",
    email: "contacto@renovacapilar.example",
    web: "https://renovacapilar.example",
    redes_sociales: { instagram: "renovacapilar", tiktok: "renovacapilar" },
    tecnicas: ["Injerto DHI", "Micropigmentación capilar"],
    idiomas: ["Español", "Alemán", "Inglés"],
    financiacion: false,
    primera_consulta_gratis: true,
    fotos: ["https://picsum.photos/seed/growwly-palma-1/800/600"],
    verificado: false,
    created_at: "2026-02-01T09:00:00.000Z",
    updated_at: "2026-06-10T09:00:00.000Z",
  },
  {
    id: "4",
    slug: "clinica-turia-valencia",
    nombre: "Clínica Turia Capilar",
    descripcion:
      "Más de 12 años realizando injertos capilares en Valencia, con planes de financiación adaptados a cada caso.",
    comunidad_autonoma: "Comunitat Valenciana",
    provincia: "Valencia",
    ciudad: "Valencia",
    zona: "Ciutat Vella",
    lat: 39.4699,
    lng: -0.3763,
    telefono: "+34 963 111 222",
    email: "citas@turiacapilar.example",
    web: "https://turiacapilar.example",
    redes_sociales: { instagram: "turiacapilar" },
    tecnicas: ["Injerto FUE", "Mesoterapia capilar"],
    idiomas: ["Español"],
    financiacion: true,
    primera_consulta_gratis: true,
    fotos: ["https://picsum.photos/seed/growwly-valencia-1/800/600"],
    verificado: true,
    created_at: "2026-01-20T09:00:00.000Z",
    updated_at: "2026-04-18T09:00:00.000Z",
  },
  {
    id: "5",
    slug: "clinica-giralda-sevilla",
    nombre: "Clínica Giralda",
    descripcion:
      "Equipo médico reducido y trato cercano; solo aceptan un número limitado de intervenciones por semana.",
    comunidad_autonoma: "Andalucía",
    provincia: "Sevilla",
    ciudad: "Sevilla",
    zona: "Nervión",
    lat: 37.3891,
    lng: -5.9845,
    telefono: "+34 954 222 333",
    email: "hola@clinicagiralda.example",
    web: "https://clinicagiralda.example",
    redes_sociales: {},
    tecnicas: ["Injerto FUE", "Injerto sin afeitado"],
    idiomas: ["Español", "Inglés"],
    financiacion: false,
    primera_consulta_gratis: false,
    fotos: ["https://picsum.photos/seed/growwly-sevilla-1/800/600"],
    verificado: false,
    created_at: "2026-02-10T09:00:00.000Z",
    updated_at: "2026-03-30T09:00:00.000Z",
  },
  {
    id: "6",
    slug: "malaga-hair-institute",
    nombre: "Málaga Hair Institute",
    descripcion:
      "Clínica orientada a pacientes internacionales de la Costa del Sol, con recepción en varios idiomas y traslado desde el aeropuerto.",
    comunidad_autonoma: "Andalucía",
    provincia: "Málaga",
    ciudad: "Málaga",
    zona: "Centro",
    lat: 36.7213,
    lng: -4.4214,
    telefono: "+34 952 333 444",
    email: "info@malagahair.example",
    web: "https://malagahair.example",
    redes_sociales: { instagram: "malagahairinstitute", facebook: "malagahairinstitute" },
    tecnicas: ["Injerto FUE", "Injerto DHI", "PRP"],
    idiomas: ["Español", "Inglés", "Alemán", "Árabe"],
    financiacion: true,
    primera_consulta_gratis: true,
    fotos: ["https://picsum.photos/seed/growwly-malaga-1/800/600"],
    verificado: true,
    created_at: "2026-01-05T09:00:00.000Z",
    updated_at: "2026-06-15T09:00:00.000Z",
  },
  {
    id: "7",
    slug: "clinica-nervion-bilbao",
    nombre: "Clínica Ibaia Capilar",
    descripcion:
      "Consulta inicial con tricólogo antes de proponer ningún tratamiento; no todos los pacientes salen con un injerto recomendado.",
    comunidad_autonoma: "País Vasco",
    provincia: "Bizkaia",
    ciudad: "Bilbao",
    zona: "Abando",
    lat: 43.263,
    lng: -2.935,
    telefono: "+34 944 555 666",
    email: "consultas@ibaiacapilar.example",
    web: "https://ibaiacapilar.example",
    redes_sociales: { instagram: "ibaiacapilar" },
    tecnicas: ["Injerto FUE", "Mesoterapia capilar"],
    idiomas: ["Español", "Euskera"],
    financiacion: true,
    primera_consulta_gratis: false,
    fotos: ["https://picsum.photos/seed/growwly-bilbao-1/800/600"],
    verificado: false,
    created_at: "2026-02-20T09:00:00.000Z",
    updated_at: "2026-05-05T09:00:00.000Z",
  },
  {
    id: "8",
    slug: "costa-blanca-hair-alicante",
    nombre: "Costa Blanca Hair Clinic",
    descripcion:
      "Especialistas en reparación de injertos anteriores mal ejecutados, además de primeras intervenciones.",
    comunidad_autonoma: "Comunitat Valenciana",
    provincia: "Alicante",
    ciudad: "Alicante",
    zona: "Centro",
    lat: 38.3452,
    lng: -0.481,
    telefono: "+34 965 777 888",
    email: "contacto@costablancahair.example",
    web: "https://costablancahair.example",
    redes_sociales: { instagram: "costablancahair" },
    tecnicas: ["Injerto FUE", "Injerto DHI", "Micropigmentación capilar"],
    idiomas: ["Español", "Inglés", "Italiano"],
    financiacion: true,
    primera_consulta_gratis: true,
    fotos: ["https://picsum.photos/seed/growwly-alicante-1/800/600"],
    verificado: true,
    created_at: "2026-01-25T09:00:00.000Z",
    updated_at: "2026-06-20T09:00:00.000Z",
  },
];
