-- Primera carga de clínicas nuevas investigadas en Mallorca
-- (growwly-clinicas-mallorca-investigacion-Agosto-2026.xlsx, filas con
-- Estado = "Nueva - especializada" / "Nueva - estética general").
-- Sin email todavía (la clínica no se ha dado de alta) y sin fotos/logo
-- (Santy los sube a mano tras revisar cada ficha) — por eso arrancan en
-- plan básico y publicado=false: no deben verse en el sitio hasta que
-- se completen y se publiquen desde el admin.
insert into clinics (
  nombre, slug, tipo_negocio, descripcion, direccion, ciudad, provincia, comunidad_autonoma, zona,
  telefono, web, lat, lng, tecnicas, servicios_adicionales, rango_precios,
  tiene_oferta, detalle_oferta, financiacion, idiomas, accesibilidad,
  rating_google, resenas_google, rating_doctoralia, resenas_doctoralia,
  horarios, plan, publicado, verificado_admin, leads_enabled
) values
('Clínica Elite Palma', 'clinica-elite-palma', 'Clínica capilar', 'Centro médico-estético con unidad de trasplante capilar', 'C/ Cardenal Rossell, 17, 07007, Palma', 'Palma', 'Illes Balears', 'Illes Balears', 'Coll d''en Rabassa', '871951211', 'https://www.elitepalma.com', 39.5536469, 2.6938378, '{"Trasplante capilar"}', '{"Medicina estética facial/corporal"}', NULL, false, NULL, false, '{}', NULL, 4.9, 49, NULL, NULL, 'Lun-Vie 10:00-13:30 y 16:30-20:00; Sáb-Dom cerrado', 'basico', false, false, false),
('Clínica El Zielo', 'clinica-el-zielo', 'Clínica capilar', 'Clínica de medicina estética, capilar y cirugía plástica', 'Av. de Alemania, 8, 07003, Palma', 'Palma', 'Illes Balears', 'Illes Balears', 'Distrito Centro', '620386048', 'https://clinica-elzielo.com', NULL, NULL, '{"Injerto FUE","FUSS y DHI"}', '{"Tratamientos capilares médico-estéticos"}', NULL, false, NULL, false, '{}', NULL, NULL, NULL, NULL, NULL, 'Horario no publicado', 'basico', false, false, false),
('OLIVA Aesthetic & Hair Clinic', 'oliva-aesthetic-hair-clinic', 'Clínica capilar', 'Clínica estética y capilar (Dra. Patricia Carabajal / Dr. Gabriel Mateo)', 'Carrer de Sant Magí, 63, 07013, Palma', 'Palma', 'Illes Balears', 'Illes Balears', 'Santa Catalina (Ponent)', '689854999', 'https://olivaclinics.com', NULL, NULL, '{"Trasplante capilar FUE","tratamientos de rejuvenecimiento capilar"}', '{"Medicina estética"}', NULL, false, NULL, false, '{"Varios idiomas (atención multilingüe)"}', 'Acceso silla de ruedas, aseo accesible, bucle magnético', 5, 251, NULL, NULL, 'Lun-Jue 09:30-19:30; Vie 09:30-17:30; Sáb-Dom cerrado', 'basico', false, false, false),
('Capilar Clinique Palma de Mallorca', 'capilar-clinique-palma-de-mallorca', 'Centro de injertos capilares', 'Clínica de injerto y trasplante capilar (cadena, Nº Registro Sanitario 3241)', '31 de Diciembre, 6 (esq. Conde de Ampurias, 12), 07004, Palma', 'Palma', 'Illes Balears', 'Illes Balears', 'Nord', '663362982', 'https://capilarclinique.com', NULL, NULL, '{"Injerto FUE","IAP (Implante de Alta Precisión)","Mesoterapia capilar"}', '{"Diseño Natural Hair"}', NULL, false, NULL, false, '{}', NULL, NULL, NULL, NULL, NULL, 'Lun-Jue 10:00-20:00; Vie 10:00-16:00', 'basico', false, false, false),
('ICAS / Dra. Stefany Mendoza', 'icas-dra-stefany-mendoza', 'Centro de injertos capilares', 'Consulta médica especializada en injerto capilar y tricología', 'Camí dels Reis, 308, Edif. 3A, planta 1 (Centro Médico Planas Salud), 07010, Palma', 'Palma', 'Illes Balears', 'Illes Balears', 'Nord', '643760434', 'https://www.drastefanymendoza.es', NULL, NULL, '{"Injerto FUE (pinzas e implanters)"}', '{}', 'Consulta 50€ (deducible del tratamiento)', false, NULL, false, '{}', 'Entorno de centro médico', NULL, NULL, NULL, NULL, 'Horario no publicado', 'basico', false, false, false),
('Clínica Mesomedic (Palma)', 'clinica-mesomedic-palma', 'Clínica estética', 'Medicina estética dirigida por el Dr. Jaime Rodríguez', 'Carrer del Bisbe Teodor Úbeda, 2 (bajo), 07014, Palma', 'Palma', 'Illes Balears', 'Illes Balears', 'Son Espanyolet / Ponent', '971905777', 'https://www.mesomedic.es', NULL, NULL, '{"Mesoterapia capilar","anticaída/regeneración capilar","láser capilar"}', '{"Medicina estética facial y corporal","criolipólisis","ondas de choque","láser","nutrición","cosmética"}', NULL, false, NULL, false, '{"Español","inglés"}', 'Sin información', 4.7, 80, NULL, NULL, 'Horario no publicado (sede Palma)', 'basico', false, false, false),
('Clínica Áureo', 'clinica-aureo', 'Clínica estética', 'Clínica multidisciplinar de estética, odontología, dermatología y nutrición (Dra. Cristina Núñez)', 'Camí de la Vileta, 39, Planta 1, Local 1, C.C. Son Moix Centre, 07011, Palma', 'Palma', 'Illes Balears', 'Illes Balears', 'Poniente / Son Moix', '871575510', 'https://www.clinicaaureo.com', NULL, NULL, '{"Mesoterapia capilar","PRP capilar","microneedling capilar"}', '{"Estética facial y corporal","cirugía plástica","dermatología","odontología","nutrición","láser"}', 'Consulta diagnóstica capilar 60€ (descontable)', false, NULL, false, '{"Español","inglés"}', 'Entrada accesible para sillas de ruedas', NULL, NULL, NULL, NULL, 'Lun-Jue 9:30-19:30; Vie 9:30-13:30; Sáb-Dom cerrado', 'basico', false, false, false),
('Clínicas Dorsia Palma', 'clinicas-dorsia-palma', 'Clínica estética', 'Cadena nacional de medicina/cirugía estética; unidad de microinjertos en Palma', 'Av. de Gabriel Roca, 54, 07015, Palma (Porto Pi)', 'Palma', 'Illes Balears', 'Illes Balears', 'Porto Pi / Ponent', NULL, 'https://www.dorsia.es', NULL, NULL, '{"Mesoterapia capilar","microinjertos capilares"}', '{"Cirugía estética","medicina estética facial/corporal","láser","nutrición/obesidad","psicología"}', NULL, true, 'Multiestetica indica ofertas activas (sin detalle)', false, '{}', 'Sin información', NULL, NULL, NULL, NULL, 'Horario no publicado', 'basico', false, false, false),
('IMAR Palma', 'imar-palma', 'Clínica estética', 'Medicina estética (Dra. Tiana Artigues)', 'Palma (dirección exacta no confirmada)', 'Palma', 'Illes Balears', 'Illes Balears', NULL, NULL, 'https://imarpalma.com', NULL, NULL, '{"PRP capilar"}', '{"Medicina estética facial y corporal"}', NULL, false, NULL, false, '{}', 'Sin información', NULL, NULL, NULL, NULL, 'Horario no publicado', 'basico', false, false, false),
('Censalud Palma', 'censalud-palma', 'Clínica estética', 'Centro médico avanzado con unidad de medicina estética capilar', 'Palma (dirección exacta no confirmada)', 'Palma', 'Illes Balears', 'Illes Balears', NULL, NULL, 'https://censalud.com', NULL, NULL, '{"Mesoterapia capilar","TrichoTest","luz LED","terapias regenerativas capilares"}', '{"Medicina estética facial y corporal"}', NULL, false, NULL, false, '{}', 'Sin información', NULL, NULL, NULL, NULL, 'Horario no publicado', 'basico', false, false, false),
('Biutibox Palma', 'biutibox-palma', 'Clínica estética', 'Medicina estética (Dra. Dayra Barón)', 'Palma (dirección exacta no confirmada)', 'Palma', 'Illes Balears', 'Illes Balears', NULL, NULL, 'https://biutibox.es', NULL, NULL, '{"Mesoterapia capilar"}', '{"Medicina estética facial y corporal"}', NULL, true, 'Primera cita médica diagnóstica gratuita', false, '{}', 'Sin información', NULL, NULL, NULL, NULL, 'Horario no publicado', 'basico', false, false, false),
('Sensemal Clinic', 'sensemal-clinic', 'Clínica estética', 'Medicina estética y regenerativa', 'Carrer del Marquès de la Fontsanta, 51, Palma', 'Palma', 'Illes Balears', 'Illes Balears', NULL, NULL, NULL, NULL, NULL, '{"Mesoterapia capilar (150€)","con dutasteride (140€)"}', '{"Neurotoxina","medicina regenerativa","facial","nutrición","tratamiento del dolor"}', '140-150€', false, NULL, false, '{}', 'Sin información', NULL, NULL, NULL, NULL, 'Horario no publicado', 'basico', false, false, false),
('Medicina Estética Dra. Inés Herráez', 'medicina-estetica-dra-ines-herraez', 'Clínica estética', 'Consulta de medicina estética en Palma', 'Carrer de Bartomeu Ferrà, 3, 1º, Centre, Palma', 'Palma', 'Illes Balears', 'Illes Balears', 'Centre', NULL, NULL, NULL, NULL, '{"Mesoterapia (capilar no confirmada explícitamente)"}', '{"Neurotoxina","tratamientos faciales","estética vascular","rejuvenecimiento"}', 'Mesoterapia facial 220€', false, NULL, false, '{}', 'Sin información', NULL, NULL, NULL, NULL, 'Horario no publicado', 'basico', false, false, false),
('Facial Esthetic Group (Clínica GBCOM)', 'facial-esthetic-group-clinica-gbcom', 'Clínica estética', 'Clínica de cirugía estética y reparadora facial (Dr. Mikel Ramos)', 'Av. Picasso, 45, Palma', 'Palma', 'Illes Balears', 'Illes Balears', NULL, NULL, 'https://www.facialestheticgroup.com', NULL, NULL, '{"Mesoterapia (capilar no confirmada)"}', '{"Cirugía ortognática y estética","estética facial","neurotoxina"}', NULL, false, NULL, false, '{}', 'Sin información', NULL, NULL, NULL, NULL, 'Horario no publicado', 'basico', false, false, false),
('Instituto Balear de Medicina Estética (IBAME)', 'instituto-balear-de-medicina-estetica-ibame', 'Clínica estética', 'Grupo de medicina estética con sedes en Palma y Port de Pollença', 'Palma y Port de Pollença (exactas no confirmadas)', 'Palma', 'Illes Balears', 'Illes Balears', 'Palma y Pueblo', NULL, 'https://ibame.es', NULL, NULL, '{"Mesoterapia (indicada para problemas capilares y fortalecimiento capilar)"}', '{"Medicina estética facial y corporal","celulitis","grasa localizada"}', NULL, false, NULL, false, '{}', 'Sin información', NULL, NULL, NULL, NULL, 'Horario no publicado', 'basico', false, false, false),
('Mallorca Aesthetic Clinic', 'mallorca-aesthetic-clinic', 'Clínica estética', 'Medicina/cirugía estética y antienvejecimiento (Palma y Cala Millor)', 'Palma y Cala Millor', 'Palma', 'Illes Balears', 'Illes Balears', 'Palma y Pueblo', '971763787 / 660938585', 'https://mac-clinica.com', NULL, NULL, '{"Capilar no confirmado explícitamente"}', '{"Medicina y cirugía estética","antienvejecimiento"}', NULL, false, NULL, false, '{"Español","inglés"}', 'Sin información', NULL, NULL, NULL, NULL, 'Horario no publicado', 'basico', false, false, false),
('Clínica Estética Manacor / Policlínic Manacor', 'clinica-estetica-manacor-policlinic-manacor', 'Clínica estética', 'Policlínico con 35 años; dirección estética por la Dra. Paula Díaz Jover (desde marzo 2022)', 'Carrer de Pius XII, 11, 07500, Manacor', 'Manacor', 'Illes Balears', 'Illes Balears', 'Centro de Manacor', '671340811', 'https://clinicaesteticamanacor.com', NULL, NULL, '{"Mesoterapia capilar","PRP capilar","medicina capilar"}', '{"Medicina/cirugía estética","antiaging","ginecoestética","obesidad","fisioterapia","ginecología","nutrición","traumatología","podología","radiología"}', 'Mesoterapia 120€', false, NULL, false, '{"Español","inglés"}', 'Sin información', NULL, NULL, 5, NULL, 'Horario no publicado', 'basico', false, false, false),
('Clínica Mesomedic (Manacor)', 'clinica-mesomedic-manacor', 'Clínica estética', 'Sede en Manacor del grupo Mesomedic', 'Av. del Parc, 60, 07500, Manacor', 'Manacor', 'Illes Balears', 'Illes Balears', 'Ronda/Parc', '971843126', 'https://www.mesomedic.es/clinica-medicina-estetica-manacor/', NULL, NULL, '{"Regeneración capilar","prevención de la caída","mesoterapia"}', '{"Medicina estética facial y corporal","botox","fillers","láser","nutrición","criolipólisis"}', NULL, false, NULL, false, '{"Español","inglés"}', 'Sí (silla de ruedas, aseos)', 4.9, 34, NULL, NULL, 'Lun-Jue 10:00-19:00; Vie 10:00-14:00', 'basico', false, false, false),
('Dr. Alfonso Vega (Manacor)', 'dr-alfonso-vega-manacor', 'Clínica estética', 'Medicina general y estética en Manacor', 'Ronda de l''Institut, 18, 07500, Manacor', 'Manacor', 'Illes Balears', 'Illes Balears', 'Centro de Manacor', NULL, NULL, NULL, NULL, '{"Tratamientos capilares","cirugía capilar (según Doctoralia)"}', '{"Neurotoxina","medicina general","urgencias","certificados médicos"}', '1ª visita medicina estética 50€; consulta online 1€', false, NULL, false, '{}', 'Sin información', NULL, NULL, NULL, NULL, 'Horario no publicado', 'basico', false, false, false),
('Clínica Estética Medisan (Inca)', 'clinica-estetica-medisan-inca', 'Clínica estética', 'Centro médico reg. sanitario 2952, en funcionamiento desde 1989 (Dra. Renée Mora Riera)', 'Carrer de la Pau, 12, 07300, Inca', 'Inca', 'Illes Balears', 'Illes Balears', 'Centro de Inca (junto Mercat Cobert)', '971880782', 'https://medisan.es', NULL, NULL, '{"Mesoterapia capilar","tratamiento de alopecia (PRP)"}', '{"Medicina estética facial (láser","hydrafacial)","corporal","depilación láser"}', NULL, true, 'Primera cita de valoración gratuita', false, '{}', 'Sin información', 4.1, 66, 0, 1, 'Lun-Jue 9:30-14:00; Lun/Mar/Jue 15:00-19:30; Vie cerrado', 'basico', false, false, false),
('Eón Clinic (Calvià)', 'eon-clinic-calvia', 'Clínica estética', 'Cirugía plástica y estética, reg. sanitario 3196 (Dra. Marta Payá)', 'Carrer de Chopin, 5, Residencial Las Adelfas, 07180, Nova Santa Ponça, Calvià', 'Calvià', 'Illes Balears', 'Illes Balears', 'Nova Santa Ponça', '971915961', 'https://eonclinicpalma.com', NULL, NULL, '{"PRP capilar / bioestimulación capilar"}', '{"Cirugía plástica","medicina estética y antienvejecimiento","dermatología","nutrición","fisioterapia"}', NULL, false, NULL, false, '{}', 'Sin información', NULL, NULL, NULL, NULL, 'Horario no publicado', 'basico', false, false, false),
('mediMAN / Medisans (Calvià)', 'mediman-medisans-calvia', 'Clínica estética', 'Concepto orientado a público masculino de Clínica Medisans (Dra. Marta Serna, desde 1996)', 'Av. del Rei Jaume I, 117, 07183, Santa Ponça, Calvià', 'Calvià', 'Illes Balears', 'Illes Balears', 'Santa Ponça', '871903504 (conflicto con 638391203)', 'https://medimanclinic.es / https://medisans.com', NULL, NULL, '{"Trasplante/injerto capilar","mesoterapia"}', '{"Medicina estética facial y corporal","depilación láser"}', NULL, false, NULL, false, '{}', 'Sin información', 3, NULL, NULL, NULL, 'Horario no publicado', 'basico', false, false, false),
('Cavimed Clínica (Portocolom, Felanitx)', 'cavimed-clinica-portocolom-felanitx', 'Clínica estética', 'Clínica con enfermería estética, ginecología y nutrición', 'Carrer d''En Cristòfor Colom, 69, Portocolom, Felanitx', 'Felanitx', 'Illes Balears', 'Illes Balears', 'Portocolom', '601921824 (conflicto con 621282842)', NULL, NULL, NULL, '{"Mesoterapia capilar (67€)"}', '{"Enfermería estética","ginecología","nutrición","medicina estética"}', '67€', false, NULL, false, '{}', 'Sin información', NULL, NULL, NULL, NULL, 'Horario no publicado', 'basico', false, false, false),
('Podostudi (Felanitx)', 'podostudi-felanitx', 'Clínica estética', 'Centro sanitario en Felanitx', 'Carrer Santueri, 18, Felanitx', 'Felanitx', 'Illes Balears', 'Illes Balears', 'Centro de Felanitx', NULL, NULL, NULL, NULL, '{"Mesoterapia capilar (67€)"}', '{"Mesoterapia corporal (60€)","podología"}', '67€', false, NULL, false, '{}', 'Sin información', NULL, NULL, NULL, NULL, 'Horario no publicado', 'basico', false, false, false),
('Clínica Port d''Andratx (Allmedica)', 'clinica-port-dandratx-allmedica', 'Clínica estética', 'Clínica médica; ''hair transplants'' listado en Fresha', 'Carrer des Saluet, 3, L1, 07157, Port d''Andratx', 'Andratx', 'Illes Balears', 'Illes Balears', 'Port d''Andratx', '971672039', NULL, NULL, NULL, '{"Trasplante capilar (por confirmar en fuente propia)"}', '{}', NULL, false, NULL, false, '{}', 'Sin información', NULL, NULL, NULL, NULL, 'Horario no publicado', 'basico', false, false, false)
on conflict (slug) do nothing;
